/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const wasm_bindgen__convert__closures_____invoke__heeb0e7632b2aa9a9: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h8da0f3bd43f20f45: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bc4ac3994b623ab: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bc4ac3994b623ab_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h904258c42d05362b: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h904258c42d05362b_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bc4ac3994b623ab_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bc4ac3994b623ab_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h904258c42d05362b_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bc4ac3994b623ab_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bc4ac3994b623ab_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bc4ac3994b623ab_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h904258c42d05362b_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bc4ac3994b623ab_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h876a16b750144eab: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hedd1986ea1c2bbe6: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hf34bfadfc85c850d: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
